
services:
  traefik:
    image: traefik:v3.6.6
    container_name: traefik
    restart: unless-stopped

    environment:
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}

    command:
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # EntryPoints
      - "--entrypoints.websecure.address=:443"

      # DNS-01 Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=digitalocean"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.delayBeforeChecks=60"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.disableChecks=true"

      # Dashboard
      - "--api.dashboard=true"

      # Logs
      - "--log.level=INFO"
      - "--accesslog=true"

    ports:
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`control.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  proxy:
    external: true
